version: '3'
services:
  livebook:
    image: livebook/livebook
    volumes:
      - ./notebooks:/home/livebook/
    ports:
      - 8080:8080
      - 8081:8081
    pull_policy: always
    # env_file:
    # - .env
